spring:
  data:
    redis:
      host: 172.23.240.125
      port: 6379
      password: 123456 #默认为空
      timeout: 3000ms
      lettuce:
        pool:
          max-idle: 6    #最大空闲数
          max-active: 10 #最大连接数
          min-idle: 2    #最小空闲数
  datasource:
    name: druidDataSource
    url: jdbc:mysql://172.23.240.125/gl
    username: remote
    password: w88346090A
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #设置空如何序列化
    default-property-inclusion: non_null
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
      accept-empty-string-as-null-object: true
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true

server:
  port: 8088
mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: org.jay.dao